name: main
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build env
        conda create -y -p ./env --file requirements.txt
        conda activate ./env

      - name: run example
        run: |
          conda activate ./env
          python domain_and_clustering_analysis.py config.yml

      - name: pytests
        run: |
          conda activate ./env
          pytest -v tests.py

